apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: LoadBalancer
  selector:
    app: netflix-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
